### ISSUE TITLE
When checking whether a package was built, take branch into consideration

### ISSUE THREAD

**Issue by giltayar** [giltayar/bilt#66]
To check that a package is built, Bilt looks for commits with `[bilt-with-bilt]` in their message. This works nicely with trunk-based development, but not so much in the OSS workflow of PR branches, where the PR branches also run `bilt`, but that bilt doesn't create real artifacts.

The solution? Add the branch name to `[bilt-with-bilt]`, i.e. `[bilt-with-bilt-main]` and when looking for this, use the current branch name. That way, the main branch can ignore commits merged from the PR branches

**Comment by zivkaziv** [comment]
Hey @giltayar can I take this issue?

**Comment by zivkaziv** [comment]
Do we have somewhere in the code the name of branch? or do we need to create some util for it?
I've found that this command can get us the name of the branch
'''
const { exec } = require('child_process');
exec('git branch --show-current', (err, stdout, stderr) => {
    if (err) {
        // handle your error
    }
});
'''

**Comment by giltayar** [comment]
@zivkaziv currently we don't know or care about the branch name, so you'll need to figure it out (your method makes sense, except that you can use the @⁨bilt/scripting-commons package to exec out.)

**Comment by zivkaziv** [comment]
Submitted PR https://github.com/giltayar/bilt/pull/70
I hope I covered the issue:)

**Comment by giltayar** [comment]
After my experience working with branches and bilt, it is now my conviction that the way Bilt figures out whether a package was built or not is wrong, and that currently the only way to use Bilt is to do trunk-based development without PRs.

So closing the issue till I figure out how to incorporate PR-based workflows into bilt.
